name: Odoo CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # ------------------------
  # 1. Build & Push Docker Image (CI)
  # ------------------------
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/odoo:latest

  # ------------------------
  # 2. Deploy to EC2 (CD)
  # ------------------------
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build  # waits for 'build' job to complete successfully

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/odoo-docker
            docker pull abdochtouki/odoo:latest
            docker-compose down
            docker-compose up -d
          EOF

      - name: Cleanup SSH Key
        run: rm private_key.pem
